/**
 * Copies hand-written TypeScript declaration files and generates a barrel
 * `index.d.ts` during the build.  Run after tsup produces the JS bundles.
 *
 * Output structure:
 *   dist/index.d.ts         — barrel re-export of all components
 *   dist/DatePicker.d.ts    — DatePicker props + component type
 *   dist/SearchSelect.d.ts  — SearchSelect props + component type
 *   dist/Label.d.ts         — Label props + component type
 */
import { copyFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const dist = resolve(root, 'dist')

// Ensure dist exists
mkdirSync(dist, { recursive: true })

const components = ['DatePicker', 'SearchSelect', 'Label']

// Copy each component's hand-written .d.ts from src/ to dist/
for (const name of components) {
  const src = resolve(root, 'src', 'components', `${name}.d.ts`)
  const dest = resolve(dist, `${name}.d.ts`)
  try {
    copyFileSync(src, dest)
  } catch (err) {
    console.error(`Failed to copy ${name}.d.ts:`, err.message)
    process.exit(1)
  }
  console.log(`  ✓ ${name}.d.ts`)
}

// Generate barrel index.d.ts (flat) — this is the main type entry
const barrel = `// Generated by scripts/copy-types.mjs — do not edit by hand.

export { DatePicker } from './DatePicker.js'
export type { DatePickerProps } from './DatePicker.js'

export { default as SearchSelect } from './SearchSelect.js'
export type { SearchSelectProps } from './SearchSelect.js'

export { Label } from './Label.js'
export type { LabelProps } from './Label.js'
`

writeFileSync(resolve(dist, 'index.d.ts'), barrel, 'utf-8')
console.log('  ✓ index.d.ts')
console.log('Types copied successfully.')
